[test-add-1-2]
description = "Check that add(1, 2) returns 3"
calldata = "0x00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000002"
expected-returndata = "0x0000000000000000000000000000000000000000000000000000000000000003"

[test-add-2-3]
description = "Check that add(2, 3) returns 5"
calldata = "0x00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000003"
expected-returndata = "0x0000000000000000000000000000000000000000000000000000000000000005"

[run-add-3-4]
description = "If there is no expected_<field> to check, just run the program with this input"
calldata = "0x00000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000004"
